services:
  traefik:
    command:
      - "--api.insecure=true" # dashboard enabled in dev
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  n8n:
    # Direct port access for local development
    ports:
      - "${N8N_PORT}:5678"

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - internal